# Generated by Django 4.2.5 on 2023-09-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(max_length=100, null=True)),
                ('Price', models.IntegerField(null=True)),
                ('Quantity', models.IntegerField(null=True)),
                ('Image', models.ImageField(null=True, upload_to='image/')),
            ],
        ),
    ]
