# Generated by Django 4.2.4 on 2023-09-25 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_list',
            old_name='Product',
            new_name='Product_name',
        ),
        migrations.RenameField(
            model_name='product_list',
            old_name='Price',
            new_name='Product_price',
        ),
        migrations.RenameField(
            model_name='product_list',
            old_name='Quantity',
            new_name='Product_quantity',
        ),
    ]
